name: soundsee
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  tflite_audio: ^0.3.0
  flutter_email_sender: ^6.0.2
  hexcolor: ^3.0.1
  snackbar: ^1.0.2
  permission_handler: ^11.3.1
  lottie: ^3.1.0
  navigator: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.9.1
  supabase_flutter: ^2.5.1
  flutter_vibrate: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/soundsee_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# flutter_native_splash:
  # android: true
  # color: "#ffffff"
  # image: lib/assets/images/soundsee_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - lib/assets/images/Google.png
   - lib/assets/images/snap.json
   - lib/assets/images/update_profile.json
   - lib/assets/images/soundsee_icon.png
   - lib/assets/images/login.json
   - lib/assets/images/signup.json
   - lib/assets/images/forgot_password.json
   - lib/assets/images/background.png
   - lib/assets/model/labels.txt
   - lib/assets/model/soundclassifier_with_metadata.tflite

  fonts:
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Regular.ttf
        weight: 400
      - asset: fonts/Ubuntu-Italic.ttf
        weight: 400
      - asset: fonts/Ubuntu-Bold.ttf
        weight: 700
